import { IsNotEmpty, IsNumber, IsOptional } from "class-validator";

export class CreateOrderDetailDto {

    //Use this to validate when in order service to update order details, if the order_detail_id is provided, it will be used to update the existing order detail, otherwise, a new order detail will be created.
    @IsOptional()
    @IsNumber()
    order_detail_id?: number; // Optional because it will be generated by the database

    @IsNotEmpty()
    @IsNumber()
    product_id: number;

    @IsNotEmpty()
    @IsNumber()
    quantity: number;
}
